version: '3.8'

name: kent-notifier

services:
# ------------------------------------LOGIN SERVICE AND DATABASE----------------------------------

  login-service:
    build: ./services/login-service/app/
    ports:
      - 8000:8000
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://login-service-db:5432/kent_notifier_user_db
    depends_on:
      - login-service-db

  login-service-db:
    image: postgres:17-alpine 
    ports:
      - 5432:5432 
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kent_notifier_user_db
    volumes:
      - login-service-vol:/var/lib/postgres/data

# ------------------------------------------------------------------------------------------------

# ----------------------------------SCRAPING SERVICE AND DATABASE---------------------------------
  # TODO: Finish writing this.

  scraping-service:
    build: ./services/scraping-service/
    ports:
      - 8001:8001

# ------------------------------------------------------------------------------------------------


# ----------------------------------------API GATEWAY---------------------------------------------

  krakend: 
    image: krakend 
    ports:
      - "8080:8080" 
    volumes:
      # bind the kraken.json config file to the volume.
      - ./krakend.json:/etc/krakend/krakend.json
    depends_on:
      - login-service

# ------------------------------------------------------------------------------------------------

# ------------------------------------------VOLUMES-----------------------------------------------
volumes:
  login-service-vol:

# ------------------------------------------------------------------------------------------------
